apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    environment: chaos
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 15
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoskube
  labels:
    app: chaoskube
spec:
  selector:
    matchLabels:
      app: chaoskube
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoskube
        role: cluster-admin
    spec:
      containers:
      - name: chaoskube
        image: quay.io/linki/chaoskube:latest
        args:
        - --interval=5s
        - --namespaces=!kube-system
        - --no-dry-run
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - port: 80
  type: NodePort
